### ISSUE TITLE
White top border cannot be removed (and can't change color)

### ISSUE THREAD

**Issue by demetrio812** [henrychavez/nativescript-bottom-navigation#10]
Hello,
while using the component with a dark theme I noticed there is a white line, I am not able to remove it.

This is my css:
```
.bottom-nav {
    tab-active-color: white;
    tab-inactive-color: #c56856;
    tab-background-color: #4A4A4A;
}
```

This is the component:
```
<BottomNavigation [tabs]="homeTabsService.tabs"
                      (tabSelected)="onBottomNavigationTabSelected($event)"
                      class="bottom-nav">
    </BottomNavigation>
```

And this is the visible white line:

![line](https://user-images.githubusercontent.com/385644/36636286-c1807fa2-19bb-11e8-9604-f06627f649e8.png)

Thanks,
Dem

**Comment by henrychavez** [comment]
Hi,
I'll release an update of the plugin with a new property to change that line color and support for iPhone X.
for now you can change that line color with the code below:
```
bottomNavigationLoaded(args) {
  const bottomNavigation = args.object;
  if (isIOS) {
    bottomNavigation.ios.keyLine.backgroundColor = new Color('green').ios;
  }
}
```
you should set that function in the `loaded` event like this
```
<BottomNavigation
  ...
  (loaded)="bottomNavigationLoaded($event)">
  ...
</BottomNavigation>
```

I'll let you know when the release is ready so you can forget this and use the new property to change that line color. 😄

**Comment by demetrio812** [comment]
Thanks for your support! The workaround works for now :)

**Comment by henrychavez** [comment]
@demetrio812 now you can use the keyLineColor property or tab-keyline-color css property to change the color of the top border 😄

**Comment by demetrio812** [comment]
This works perfectly! Thank you!
