### ISSUE TITLE
I: TypeError: AHBottomNavigation is not a constructor

### ISSUE THREAD

**Issue by nea** [henrychavez/nativescript-bottom-navigation#11]
### Which platform(s) does your issue occur on?
- Android
- 7.1.1
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.4.2
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.1
- Plugin(s): 
`"dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.2.0",
    "nativescript-bottom-navigation": "^1.2.0",
    "nativescript-bottombar": "^3.0.8",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.5.2",
    "tns-core-modules": "~3.4.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.6.0",
    "typescript": "~2.6.2"
  }`

### Please, tell us how to recreate the issue in as much detail as possible. 
I create a new TNS project from the NG template and wanted to add the bottom bar, as in your demo app.

The error is:
> System.err: Calling js method onCreateView failed
> System.err: TypeError: AHBottomNavigation is not a constructor
> System.err: File: "file:///data/data/org.nativescript.xyz/files/app/tns_modules/nativescript-bottom-navigation/bottom-navigation.js, line: 22, column: 26

**Comment by nea** [comment]
I just made a tns update to 3.4.3 and now the error is

> System.err: TypeError: Cannot read property 'android' of null
> System.err: File: "file:///data/data/org.nativescript.xyz/files/app/tns_modules/nativescript-bottom-navigation/bottom-navigation.js, line: 50, column: 79

**Comment by nea** [comment]
My bad!

I forgot to copy the icons. I skipped over that line when jumping directly to the Angular description. Maybe repeat that information in that section for the people like me who cannot wait to test this cool plugin ^^'


Thanks a lo

**Comment by henrychavez** [comment]
@nea haha don't worry I'm glad that you can solve your problem.

**Comment by MuthuHere** [comment]
Hi, Am also facing the same error. i have added only one image ic_home in all android folders and also in iOS folder. But still i am getting the following error. 
[https://imgur.com/a/9w7vciz](url)
Can you please get me out from this:-( It would be grateful :-) @henrychavez @nea  Please guide me

**Comment by henrychavez** [comment]
Hi @MuthuHere,

I suggest you check which icons you are using with the plugin if you are using the same ic_home for all your tabs is fine but if you are using different icons for each tab and you only have the ic_home I suggest you import the rest.

**Comment by MuthuHere** [comment]
Yes now i changed the icons as mentioned in your code. but still i am getting the same error:( Please find the below 
![untitled](https://user-images.githubusercontent.com/18752533/39402252-c8b52654-4b77-11e8-9ed1-5859758cec42.png)


and the error snap is here

![error](https://user-images.githubusercontent.com/18752533/39402275-624d66c8-4b78-11e8-9050-8e12abed5fb8.png)

Here is some details for your reference,

**npm -version  :  5.8.0**
** tns-core-modules@4.0.0** 

Thanks !

**Comment by henrychavez** [comment]
I already update the plugin and was test it with the latest version of nativescript.

Please update the plugin in your project

**Comment by MuthuHere** [comment]
Hi Henry,
Yes, Basically I am an Android Developer. So I kept all required images in all the drawable folders as per size. And i have added a screenshot for iOS folder. Hope I have done correctly. But still error is there same error which i sent in last mail. Please help what i did wrong.

**Comment by henrychavez** [comment]
@brunoziie Hi! 

This issue was closed because MuthuHere was using the xml example in a project with angular.

Please be sure that you have your icons inside App_resources and you are following the example code for angular.

**Comment by max-pro** [comment]
Hello 
I'm using nativescript-vue. I saved all icons in app_resource and still i getting error AHBottomNavigation is not a constructure

**Comment by NithinSastry** [comment]
> @MuthuHere just try "tns run android --clean"

Thanks a lot. Ran this command and built the app again. It worked!
