### ISSUE TITLE
Q: Image format for icons

### ISSUE THREAD

**Issue by nea** [henrychavez/nativescript-bottom-navigation#13]
### Which platform(s) does your issue occur on?
- Android
- 7.1.1
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.4.2
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.1
- Plugin(s): 
`"dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.2.0",
    "nativescript-bottom-navigation": "^1.2.0",
    "nativescript-bottombar": "^3.0.8",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.5.2",
    "tns-core-modules": "~3.4.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.6.0",
    "typescript": "~2.6.2"
  }`

### Please, tell us how to recreate the issue in as much detail as possible. 
Hi

I used the Demo example and copied everything to my own environment and it runs perfectly.

Now, I want to change the icons and used http://nsimage.brosteins.com/ to create new icons. I set the icons in the template (e.g. instead of ic_home my own icon) and it doesn't crash or anything, but the icon is a plain white circle.
The image itself is of a circular shape. Does the image only use the outline? Or are there any other conditions to meet? Can no colored, fully fledged images be used?

Thanks

**Comment by henrychavez** [comment]
Hi,

the image that you are using was .jpg before using the nativescript tool?

**Comment by nea** [comment]
Hey @henrychavez 

No, png. Actually this very popular logo ^^
![vwlogo](https://user-images.githubusercontent.com/392035/37475790-ccfa2f74-2873-11e8-91c4-e5485cb76209.png)

Best

**Comment by henrychavez** [comment]
Ok, now I understand whats wrong. That kind of image can't be icons,
usually the icons has a background with empty spaces or no background and
just strokes.

**Comment by nea** [comment]
Hey @henrychavez 

So, I cannot use any colored, fully fledged images but only "real" icons, correct?


Cheers
