### ISSUE TITLE
Error java.lang.ArrayIndexOutOfBoundsException: length=5; index=5 if Tabs greater than 3(as SHOWN in demo)

### ISSUE THREAD

**Issue by paidTrainee27** [henrychavez/nativescript-bottom-navigation#15]
Hi,
I'm getting array out of bound error when I increase the number of tabs from 3 to any number like 5.
I know this may not be a bug but rather enhancement/extension.
But hope to see it implemented along with horizontal auto scroll of tabs to see hidden tabs(4 and 5)
Code:
`<BottomNavigation activeColor="red"
                      inactiveColor="yellow"
                      backgroundColor="black"
                      keyLineColor="black"
                      (tabSelected)="onBottomNavigationTabSelected($event)"
                      row="1">
        <BottomNavigationTab title="First" icon="ic_home_black_24dp"></BottomNavigationTab>
        <BottomNavigationTab title="Second" icon="ic_home_black_24dp"></BottomNavigationTab>
        <BottomNavigationTab title="Third" icon="ic_home_black_24dp"></BottomNavigationTab>
        <BottomNavigationTab title="Forth" icon="ic_home_black_24dp"></BottomNavigationTab>
        <BottomNavigationTab title="Fifth" icon="ic_home_black_24dp"></BottomNavigationTab>
        <BottomNavigationTab title="Sixth" icon="ic_home_black_24dp"></BottomNavigationTab>
    </BottomNavigation>`

Error:
`System.err: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
System.err:     at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createC
lassicItems(AHBottomNavigation.java:459)
System.err:     at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createI
tems(AHBottomNavigation.java:282)
System.err:     at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.onSizeC
hanged(AHBottomNavigation.java:150)
System.err:     at android.view.View.sizeChange(View.java:18129)
System.err:     at android.view.View.setFrame(View.java:18091)
System.err:     at android.view.View.layout(View.java:18006)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5817)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(Commo
nLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:
353)
System.err:     at android.view.View.layout(View.java:18010)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5817)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(Commo
nLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:
353)
System.err:     at android.view.View.layout(View.java:18010)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5817)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(Commo
nLayoutParams.java:222)
System.err:     at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout
.java:73)
System.err:     at android.view.View.layout(View.java:18010)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5817)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:34
4)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
System.err:     at android.view.View.layout(View.java:18010)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5817)
System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1
742)
System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:
1585)
System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
System.err:     at android.view.View.layout(View.java:18010)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5817)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:34
4)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
System.err:     at com.android.internal.policy.PhoneWindow$DecorView.onLayout(Ph
oneWindow.java:3175)
System.err:     at android.view.View.layout(View.java:18010)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5817)
System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:277
6)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java
:2477)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1544)

System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.
java:7607)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.j
ava:911)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:686
)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:622)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Chor
eographer.java:897)
System.err:     at android.os.Handler.handleCallback(Handler.java:739)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7402)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(Zy
goteInit.java:1230)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

ActivityManager: Process org.nativescript.HelloWorld (pid 8788)(adj 0) has died(
122,268)
ActivityManager: cleanUpApplicationRecord -- 8788
ActivityManager: removeProcessNameLocked mProcessNames.remove pid=8788 ,hash=158
870356 ,name=org.nativescript.HelloWorld`

**Comment by henrychavez** [comment]
Hi,

this plugin follows the Material design specs for Bottom navigation and the max number of items is 5 and you are using 6.

I'll close this because doesn't match with the Material design specs of what this plugin is based.

Best.
