### ISSUE TITLE
Demo app cannot run and confused about how to use it to navigate

### ISSUE THREAD

**Issue by hanglearning** [henrychavez/nativescript-bottom-navigation#17]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?

iOS emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
3.4.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
The above are all from the latest angular sample app in this repository

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
After I downloaded the project and add the iOS platform for demo-angular, I ran "tns run ios --emulator", and then got this error:
file:///app/item/items.component.js:5:47: JS ERROR Error: Could not find module 'nativescript-bottom-navigation'. Computed path '/Users/myname/Library/Developer/CoreSimulator/Devices/BB3CE3BE-B73A-4242-9A16-576F446FD80C/data/Containers/Bundle/Application/5BC55D01-7E8B-4F10-83F2-45FA7B44CF58/demoangular.app/app/tns_modules/nativescript-bottom-navigation'.
![screen shot 2018-04-12 at 9 26 20 pm](https://user-images.githubusercontent.com/13460425/38680167-360cfce6-3e98-11e8-98c2-c77f5cce6f7a.png)

Wanted to know how to solve it so I might get a better idea of how to navigate pages by this plugin.
Thanks!

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.
It is this repository.

**Comment by henrychavez** [comment]
Hi,

to run the demo app you need to do the following steps:

1.- After cloning this repository navigate to the src folder
`cd ~/nativescript-bottom-navigation/src`

2.- Then run
`npm run demo.angular.{platform}`

3.- Enjoy!

About the navigation, there are different approaches:

1.- You can use a `route-outlet` and perform a navigation `tabSelected` event.
```
<GridLayout rows="*, auto">
    <StackLayout row="0">
       <router-outlet></router-outlet>
    </StackLayout>
    <BottomNavigation activeColor="red"
                      inactiveColor="yellow"
                      backgroundColor="black"
                      keyLineColor="black"
                      (tabSelected)="onBottomNavigationTabSelected($event)"
                      row="1">
        <BottomNavigationTab title="First" icon="ic_home"></BottomNavigationTab>
        <BottomNavigationTab title="Second" icon="ic_view_list"></BottomNavigationTab>
        <BottomNavigationTab title="Third" icon="ic_menu"></BottomNavigationTab>
    </BottomNavigation>
</GridLayout>
```
2- You can use ngSwitch from angular to show a component base on a key and this key will change when the `tabSelected ` event is fired.
```
<GridLayout rows="*, auto">
    <StackLayout row="0" [ngSwitch]="selectedTab">
       <home-component *ngSwitchCase="componentKey">...</home-component>
       <products-component *ngSwitchCase="componentKey">...</products-component>
       <settings-component *ngSwitchDefault>...</settings-component>
    </StackLayout>
    <BottomNavigation activeColor="red"
                      inactiveColor="yellow"
                      backgroundColor="black"
                      keyLineColor="black"
                      (tabSelected)="onBottomNavigationTabSelected($event)"
                      row="1">
        <BottomNavigationTab title="First" icon="ic_home"></BottomNavigationTab>
        <BottomNavigationTab title="Second" icon="ic_view_list"></BottomNavigationTab>
        <BottomNavigationTab title="Third" icon="ic_menu"></BottomNavigationTab>
    </BottomNavigation>
</GridLayout>
```

**Comment by hanglearning** [comment]
Hi Henry!

Thanks for your detailed explanation! I was actually gonna ask if we could use it with <router-outlet> and how we could use it... after I have run the demo app and see if I couldn't figure that out myself, but you just gave out the guides ahead! I appreciate it! 👍

Well, one more thing though. When I used <router-outlet>, I always set up something like: 

```
export const AppRoutes: any = [
	{path: "", component: LoginComponent},
	{path: "register", component: RegisterComponent},
	{path: "guest", component: GuestComponent}
];
```

and here, although you mentioned that I should use it with the `tabSelected` event, I still am not so sure how I can bind my pages to each of the navigation buttons... The only thing I have figured out is to use it like 

```
        onBottomNavigationTabSelected(args: OnTabSelectedEventData): void {
		if (args.newIndex == 0) {
                          this.router.navigate(["login"]);
		} else if (args.newIndex == 1) {
			this.router.navigate(["register"]);
		} else {
			this.router.navigate(["guest"]);
		}
	}
```
but still this wouldn't bind the buttons with <router-outlet>, right?

So could you elaborate a bit more on the usage of <router-outlet></router-outlet> with the `tabSelected` event? Plus, thanks for your time and efforts for making such an awesome nativescript bottom navigation plugin!

PS: the demo app runs good! 😄

**Comment by henrychavez** [comment]
To use the `router-outlet` approach you to configure child routes or nested routes but since v4 of Nativescript was released now you can use `page-router-outlet` to work without child routes an have a better implementation of the navigation because `router-outlet` recreate each component on navigation and doesn't provide you a history of navigation.

My recommendation if you are not familiar with the latest version  of Nativescript is to use the `ngSwitch` approach is better for your main view

**Comment by hanglearning** [comment]
Oh yea thanks for your recommendation! I will take a closer look at the page-router-outlet and see if I cannot figure it out easily, I will go for ngSwitch. Really appreciate your response and help!😊

**Comment by henrychavez** [comment]
You're welcome 😄 

Happy coding!
