### ISSUE TITLE
Does not exist method on

### ISSUE THREAD

**Issue by davidsekielyk** [henrychavez/nativescript-bottom-navigation#2]
in the loaded function in the main-page.ts file

`export function loaded(args) {
  let bar: BottomNavigation = args.object;
  bar.on('tabSelected', tabSelected);
}`

mark me that the on method does not exist

I fixed the index of the plugin and it is true, it does not exist

`Import { BottomNavigationBase, BottomNavigationTabBase } from './bottom-navigation.common';`
`import { EventData } from 'tns-core-modules/data/observable';`

`export declare interface OnTabSelectedEventData extends EventData {
  oldIndex: number;
  newIndex: number;
}`

`export declare class BottomNavigation extends BottomNavigationBase {
  private _delegate;
  public tabs: BottomNavigationTab[];
  public selectedTabIndex: number;
  public activeColor: string;
  public inactiveColor: string;
  public backgroundColor: string;
  constructor();
  readonly ios: any;
  createTabs(tabs: BottomNavigationTab[]): void;
  selectTab(index: number): void;
  protected selectTabNative(index: number): void;
}`

`export declare class BottomNavigationTab extends BottomNavigationTabBase {
  constructor(title: string, icon: string, parent?: WeakRef<BottomNavigationBase>);
}`

**Comment by henrychavez** [comment]
@davidsekielyk 
Can you show me your implementation and the version of nativescript?
I just test it and it's working without problems. Please check the code in the demo folder.

**Comment by henrychavez** [comment]
@davidsekielyk since this is not an issue, I'll going to close it.
