### ISSUE TITLE
An uncaught Exception occurred on "main" thread.

### ISSUE THREAD

**Issue by hanijazzar** [henrychavez/nativescript-bottom-navigation#20]
Just trying to use it for the first time, followed the exact instructions and got this exception:
(Running on Android v8.0 on a physical android device  - using Angular version)

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sg.SportsGame/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onStart failed

TypeError: Cannot read property 'android' of null
File: "file:///data/data/org.sg.SportsGame/files/app/tns_modules/nativescript-bottom-navigation/bottom-navigation.js, line: 50, column: 79

StackTrace: 
Frame: function:'BottomNavigation.createTabs', file:'file:///data/data/org.sg.SportsGame/files/app/tns_modules/nativescript-bottom-navigation/bottom-navigation.js', line: 50, column: 80
Frame: function:'BottomNavigation.(anonymous function)', file:'file:///data/data/org.sg.SportsGame/files/app/tns_modules/nativescript-bottom-navigation/bottom-navigation.js', line: 60, column: 14
Frame: function:'applyAllNativeSetters', file:'file:///data/data/org.sg.SportsGame/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 961, column: 28
Frame: function:'initNativeView', file:'file:///data/data/org.sg.SportsGame/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js', line: 905, column: 9
....

**Comment by henrychavez** [comment]
Can you please review if you have the icons included in your project?

**Comment by hanijazzar** [comment]
Yes I'm sure I have them and with the correct name. I saw the issue in the alternative bottombar repo. That one actually worked so I ended up using it instead
