### ISSUE TITLE
When the page is switched, the page will be rendered again. Is there any way to avoid it?

### ISSUE THREAD

**Issue by hawind** [henrychavez/nativescript-bottom-navigation#22]
### Which platform(s) does your issue occur on?
- Android
- 7.0
- xiaomi max

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): 4.0.1
- Plugin(s): "dependencies": {
    "angular/animations": "~5.2.0",
    "angular/common": "~5.2.0",
    "angular/compiler": "~5.2.0",
    "angular/core": "~5.2.0",
    "angular/forms": "~5.2.0",
    "angular/http": "~5.2.0",
    "angular/platform-browser": "~5.2.0",
    "angular/platform-browser-dynamic": "~5.2.0",
    "angular/router": "~5.2.0",
    "nativescript-angular": "~5.2.0",
    "nativescript-bottom-navigation": "^1.3.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.5.2",
    "tns-core-modules": "^4.0.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "angular/compiler-cli": "~5.2.0",
    "ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.6.0",
    "nativescript-dev-webpack": "^0.11.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "tslint": "^5.9.1",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 

Hello, the author is a great plug-in, but I found a problem when I used it. When you switch the page, the page will be re - rendered. Is there any way to avoid it

**Comment by hawind** [comment]
I used demo-angular, for example, I rolled the ItemsComponent to the end, then switched to the other pages, and then switched back to find that the page was rerendered, and did not know whether nativescript could prevent repeated rendering. I am very sorry, I am from China and do not understand English, so I rely on translation to communicate with you.

**Comment by henrychavez** [comment]
ok, yes the components are re-rendered is a common behavior using ngSwitch but I think with the latest version of Nativescript we can use the page-router-outlet so when you change of page base on the option selected the previous component will conserve his last statement.

I didn't have the time to try an example using the page-router-outlet but I'll try to do it this week.

**Comment by Nurgunkalol** [comment]
any news?
