### ISSUE TITLE
Clicking on an already active tab doesn't send a tabSelected event.

### ISSUE THREAD

**Issue by diantox** [henrychavez/nativescript-bottom-navigation#27]
### Which platform(s) does your issue occur on?
- Android Emulator (Android 8.1.0 or API 27)
- OnePlus 6 (Android 8.1.0 or API 27)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.1.2
- Cross-platform modules: 3.4.1
- Runtime(s): tns-android 3.4.1
- Plugin(s): nativescript-bottom-navigation 1.2.X

### Please, tell us how to recreate the issue in as much detail as possible. 
In any NativeScript project using nativescript-bottom-navigation, trying to select an already selected tab won't send the `tabSelected` event.

It looks like (`src/bottom-navigation.android.ts:39`)[https://github.com/henrychavez/nativescript-bottom-navigation/blob/master/src/bottom-navigation.android.ts#L39] is causing this issue on Android. I can't find a similar line in (https://github.com/henrychavez/nativescript-bottom-navigation/blob/master/src/bottom-navigation.ios.ts)[src/bottom-navigation.ios.ts].

Looking at nativescript-bottom-navigation's code, this is intended behavior. In my case, I'm working on an application where clicking on a bottom navigation tab will take you to an index page, and any page under that index page will keep that bottom navigation tab active. I want to be able to click on the already active bottom navigation tab to bring me back to the index page.

How an application handles clicking on an already active tab should be up to the developer IMO.

Thanks!
- Miras

**Comment by henrychavez** [comment]
Hi,

I'm agree with you on this:
> How an application handles clicking on an already active tab should be up to the developer IMO

but as the event says is only fired when a tab is selected, so I think a better approach is creating a new event like tabReselect or tabClicked that would be fired when the user click an already selected tab, so you can use tabSelect to perform some navigations, etc and the tabClicked or tabReselected to perform other stuffs like you are mention and have a more organized code.

Without mention that if I remove the actual behavior for that event will affect to all the people already using the plugin.

Let me know what you think and please feel free and create a pull request if you want to contribute :D

**Comment by M1ras** [comment]
You make a good point, changing how `tabSelected` behaves may break applications that use this plugin. I like the idea of a `tabReselected` event. I've been developing Android apps for as few years, so I can develop the Android side of `tabReselected`.

Thanks for the quick response!

**Comment by henrychavez** [comment]
Great! 👍 I'll do the iOS side
