### ISSUE TITLE
Vue implementation

### ISSUE THREAD

**Issue by aroms** [henrychavez/nativescript-bottom-navigation#28]
Any documentation to implement this amazing pluging with nativescript-vue (VueJS)?

**Comment by ecnerret-adajet** [comment]
Waiting for this also. thanks

**Comment by henrychavez** [comment]
Hi,
you can check this [link](https://nativescript-vue.org/en/docs/getting-started/nativescript-plugins/)

**Comment by henrychavez** [comment]
Hi, 

As I mention before in the docs you can find a way to use any Nativescript plugin with Vue using the following code in ur app.js or main.js

Vue.registerElement(“BottomNavigation”, () => require(“nativescript-bottom-navigation”))

Then u can use <BottomNavigation> in ur html

**Comment by captainmike** [comment]
Thanks for the good work. I'd just like to add that it would be really helpful to add a Vue example to readme for those less familiar Angular.

**Comment by henrychavez** [comment]
Hi @captainmike 

Great Idea! I'll do that tonight.

**Comment by suryaadtmaja** [comment]
> Hi @captainmike
> 
> Great Idea! I'll do that tonight.

Thank you henry! Good Luck!!!

**Comment by henrychavez** [comment]
@suryaadtmaja did you have the change to look the modifications to the `Readme.md` file?

Please tell me if I'm missing something :D

**Comment by suryaadtmaja** [comment]
> @suryaadtmaja did you have the change to look the modifications to the `Readme.md` file?
> 
> Please tell me if I'm missing something :D
I was doing that before, but no luck, it's still getting an error.

**Comment by suryaadtmaja** [comment]
Anyway thanks for the response @henrychavez  ,
I was doing that before, but no luck, it's still getting an error.

**Comment by henrychavez** [comment]
@suryaadtmaja can u send me the error so I can help u

**Comment by issibi** [comment]
hi, how do i to get the tabSelected in Vue ?

methods: {
onBottomNavigationTabSelected(tabSelected) {
    console.log(tabSelected);
  }
}

prints the event object but no idea how to get the selectedTabIndex.

tabSelected.selectedTabIndex or similar is always undefined.
could you show an example how to get the selected tab in Vue ? 
In the docs there are  examples for angular and JS but not for Vue.

thnx for help.

**Comment by henrychavez** [comment]
can you show me the value of tabSelected? 
what I'm sending is the full event object where you can find the the following: 
```
{
      eventName: 'tabSelected',
      object: this, (This is a reference to BottomNavigation instance)
      oldIndex: this.selectedTabIndex || 0,
      newIndex: index
}
```
Please send the output of ur `console.log(tabSelected);` for more detail

**Comment by henrychavez** [comment]
Ok everything is ok you can follow the example code in the repo, as I mentioned before what you receive is an object like this 
```
{
      eventName: 'tabSelected',
      object: this, (This is a reference to BottomNavigation instance)
      oldIndex: this.selectedTabIndex || 0,
      newIndex: index
}
```
so if you need the new Index you can do `args.newIndex``

you always will receive the event object with information of the old and new index, also the object which you can use to manipulate the instance of the bottom navigation class.

You can follow the examples in the repo or the readme, the logic doesn't change no matter you are using Vue, Angular or just Javascript.

**Comment by henrychavez** [comment]
no problem :)

Happy Coding!
