### ISSUE TITLE
cannot run ios js demo (Error: Building UI from XML)

### ISSUE THREAD

**Issue by tyt2y3** [henrychavez/nativescript-bottom-navigation#3]
Hi, I am trying to run the demo (non angular) on ios.
after `npm install` and `tns run ios`
it gives an error
```
JS ERROR Error: Building UI from XML. @file:///app/main-page.xml:12:9
```
which is referring to this line
```
<bottomBar:BottomNavigation class="bottom-nav"
```

I think I am missing some setup here. Sorry for being a novice

**Comment by henrychavez** [comment]
Well... I recommend you to clone the repository go to `src` folder an then run this command
`npm run demo.ios`

Is not necessary to run `npm install` the command does.

Tell me if it works

**Comment by tyt2y3** [comment]
Great... it works!
So I think the trick is to `tns run ios --syncAllFiles`
I found syncAllFiles to be an undocumented switch in man page

**Comment by henrychavez** [comment]
No, the first time didn't work because in this case you need to build the
plugin(ts to js).

You can read more about how the plugins work in nativescript docs.

Happy coding
