### ISSUE TITLE
Error: Invalid boolean: undefined Vuejs 

### ISSUE THREAD

**Issue by mooeezz** [henrychavez/nativescript-bottom-navigation#34]
### Which platform(s) does your issue occur on?
- Android
- 8.1
-  device

### Please, provide the following version numbers that your issue occurs with:

template = https://github.com/nativescript-vue/vue-cli-template/

Error: Invalid boolean: undefined

System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
System.err:     at android.app.Fragment.performCreateView(Fragment.java:2508)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
System.err:     at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2412)
System.err:     at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2191)
System.err:     at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2147)
System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2048)
System.err:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
System.err:     at android.os.Handler.handleCallback(Handler.java:790)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:171)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6633)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by ecnerret-adajet** [comment]
Hi @mooeezz  may I know how you fix this ? I'm also having the same issue as this

**Comment by mooeezz** [comment]
remove devtools toast socket from package.json
