### ISSUE TITLE
iOS Safe zone support for new Material Design

### ISSUE THREAD

**Issue by alexandruantonica** [henrychavez/nativescript-bottom-navigation#38]
The last Podfile had safe zone support but this one don't.

**Comment by henrychavez** [comment]
Look @alexandruantonica 
![simulator screen shot - iphone x - 2018-10-27 at 17 11 55](https://user-images.githubusercontent.com/6098329/47609797-73608180-da0b-11e8-9000-5a6048960033.png)

**Comment by alexandruantonica** [comment]
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.NewFuckingApp",
    "tns-ios": {
      "version": "3.4.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.2.0",
    "nativescript-bottom-navigation": "^1.4.1",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.5.5",
    "tns-core-modules": "3.4.1",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "~0.6.0",
    "nativescript-dev-webpack": "~0.9.1",
    "typescript": "~2.6.2",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0",
    "copy-webpack-plugin": "~4.3.0",
    "raw-loader": "~0.5.1",
    "css-loader": "~0.28.7",
    "nativescript-worker-loader": "~0.8.1",
    "resolve-url-loader": "~2.2.1",
    "extract-text-webpack-plugin": "~3.0.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.4"
  }
}


![image](https://user-images.githubusercontent.com/12050715/47614489-840b0900-da98-11e8-93af-702bba988961.png)

**Comment by henrychavez** [comment]
update your tns-ios version to 4.2.0
