### ISSUE TITLE
tabs property not rendering

### ISSUE THREAD

**Issue by ozma999** [henrychavez/nativescript-bottom-navigation#4]
### Which platform(s) does your issue occur on?
- iOS/Android/Both 

### Please, provide the following version numbers that your issue occurs with:
-  tns version
3.2.1

## Description
-tabs doesn't render using [tabs] property, it works when declaring the tabs in the HTML directly though.
#### HTML

"<GridLayout rows="*, auto">
    <StackLayout row="0">
       <Label text="content"></Label>
    </StackLayout>
    <BottomNavigation [tabs]="tabs"
                      activeColor="red"
                      inactiveColor="yellow"
                      backgroundColor="black"
                      (tabSelected)="onBottomNavigationTabSelected($event)"
                      row="1"></BottomNavigation>
</GridLayout>"

#### TS

import { Component, OnInit } from "@angular/core";
import { BottomNavigation, BottonNavigationTab, OnTabSelectedEventData } from 'nativescript-bottom-navigation';

@Component(
  {
    selector: "ns-app",
    moduleId: module.id,
    templateUrl: "./app.component.html",
  }
)
export class AppComponent {

  public tabs: BottonNavigationTab[] = [
    new BottomNavigationTab('First', 'ic_home'),
    new BottomNavigationTab('Second', 'ic_view_list'),
    new BottomNavigationTab('Third', 'ic_menu')
  ];

  onBottomNavigationTabSelected(args: OnTabSelectedEventData): void {
    console.log(`Tab selected:  ${args.oldIndex}`);
  }
}

**Comment by henrychavez** [comment]
I notice that you are using the example code but do you have the icons on your resource folder?

**Comment by ozma999** [comment]
yes in fact the tabs work when i declare the tabs on the HTML like this

 <BottomNavigation activeColor="red"
                      inactiveColor="yellow"
                      backgroundColor="black"
                      (tabSelected)="onBottomNavigationTabSelected($event)"
                      row="1">
        <BottomNavigationTab title="First" icon="ic_home"></BottomNavigationTab>
        <BottomNavigationTab title="Second" icon="ic_view_list"></BottomNavigationTab>
        <BottomNavigationTab title="Third" icon="ic_menu"></BottomNavigationTab>
    </BottomNavigation>

but not when i use [tabs] property

**Comment by henrychavez** [comment]
Yes I already confirm the issue I'll fixing now. 

I'll let you know when the fix is done

**Comment by ozma999** [comment]
Thanks .

**Comment by henrychavez** [comment]
@ozma999 the issue was fixed and also included in the new version 1.0.2
