### ISSUE TITLE
Unexpected value DIRECTIVES when trying to build

### ISSUE THREAD

**Issue by gleibfried** [henrychavez/nativescript-bottom-navigation#43]
Hello, I have an issue when I try to build my app after adding the plugin. In develop run mode there's no issue, but now I'm trying to build the app to get the APK it fails with this message:

> Unexpected value 'DIRECTIVES in /project/node_modules/nativescript-bottom-navigation/angular/nativescript-bottom-navigation.directives.js' declared by the module 'NativescriptBottomNavigationModule in /project/node_modules/nativescript-bottom-navigation/angular/nativescript-bottom-navigation.module.d.ts'. Please add a @Pipe/@Directive/@Component annotation.

Do you have an idea? Thanks!

**Comment by henrychavez** [comment]
Hi

can you provide more information about the version that you are using?

your package.json by example

**Comment by gleibfried** [comment]
I currently am in version "^1.4.1", that's what tns added me automatically
when I installed

Le ven. 9 nov. 2018 à 16:04, Henry Chávez <notifications@github.com> a
écrit :

**Comment by gleibfried** [comment]
Sure, there you go:
`{
  "description": "",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "",
    "hooks": [
      {
        "type": "after-prepare",
        "script": "after-prepare.js"
      }
    ],
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "6.1.4",
    "@angular/common": "6.1.4",
    "@angular/compiler": "6.1.4",
    "@angular/core": "6.1.4",
    "@angular/forms": "6.1.4",
    "@angular/http": "6.1.4",
    "@angular/platform-browser": "6.1.4",
    "@angular/platform-browser-dynamic": "6.1.4",
    "@angular/router": "6.1.4",
    "@fortawesome/fontawesome": "1.1.8",
    "@fortawesome/fontawesome-free": "5.2.0",
    "angular-l10n": "5.0.0",
    "font-awesome": "4.7.0",
    "lodash": "4.17.10",
    "mime": "^2.3.1",
    "moment": "2.22.2",
    "nativescript-angular": "6.1.0",
    "nativescript-aws-sdk": "0.0.4",
    "nativescript-background-http": "^3.3.0",
    "nativescript-bottom-navigation": "^1.4.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-drop-down": "4.0.1",
    "nativescript-fabric": "^2.0.2",
    "nativescript-google-maps-sdk": "2.6.1",
    "nativescript-mediafilepicker": "^1.0.7",
    "nativescript-modal-datetimepicker": "1.1.4",
    "nativescript-permissions": "^1.2.3",
    "nativescript-pulltorefresh": "^2.1.1",
    "nativescript-secure-storage": "2.3.0",
    "nativescript-socket.io": "^0.9.0",
    "nativescript-theme-core": "1.0.4",
    "nativescript-toast": "1.4.6",
    "nativescript-ui-autocomplete": "3.9.0",
    "nativescript-ui-calendar": "3.8.0",
    "nativescript-ui-chart": "3.8.0",
    "nativescript-ui-dataform": "3.7.0",
    "nativescript-ui-gauge": "3.7.1",
    "nativescript-ui-listview": "3.6.0",
    "nativescript-ui-sidedrawer": "4.3.0",
    "nativescript-vue": "1.3.1",
    "ngx-logger": "3.0.5",
    "reflect-metadata": "0.1.12",
    "rxjs": "6.2.2",
    "tns-core-modules": "^4.2.1",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "6.1.4",
    "@ngtools/webpack": "6.1.5",
    "@types/lodash": "4.14.116",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "cross-env": "^5.2.0",
    "lazy": "1.0.11",
    "mkdirp": "^0.5.1",
    "nativescript-dev-typescript": "0.7.3",
    "nativescript-dev-webpack": "0.15.1",
    "node-sass": "4.9.3",
    "typescript": "2.9.2"
  }
}`

Thanks for the fast answers :)

**Comment by gleibfried** [comment]
Sure! I try with this one:

> cross-env BUILD_PROFILE=staging tns build android --clean --compileSdk 26 --release --key-store-path SOMEPATH --key-store-password SOMEPASSWORD --key-store-alias SOMEKEY --key-store-alias-password SOMEPASSWORD --bundle --env.uglify --env.aot --env.snapshot

**Comment by henrychavez** [comment]
Hi @gleibfried 

sorry for the delay, I already fix the problem and will be available in a few moments in the version 1.4.4

😄

**Comment by gleibfried** [comment]
Perfect, thanks a lot!
