### ISSUE TITLE
Icons - Vue

### ISSUE THREAD

**Issue by romucci** [henrychavez/nativescript-bottom-navigation#44]
Sorry for my ignorance, but when you say " add your icons to App_Resource", where are the icons supposed to be coming from? :D

**Comment by henrychavez** [comment]
I recommend you to read the docs for [ios](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/custom-icons/) and [Android](https://developer.android.com/guide/practices/ui_guidelines/icon_design)

but If you want to use material icons [here](https://material.io/tools/icons/?icon=accessibility&style=baseline) you can download the png files for android & iOS

But if you wanna use any other icon just download the png files in the sizes that each platform specifies:

For android you can use the [assets generator](https://romannurik.github.io/AndroidAssetStudio/index.html) to create custom icons
