### ISSUE TITLE
[Vue] How to change the stacklayout content when a tab is selected?

### ISSUE THREAD

**Issue by syahnur197** [henrychavez/nativescript-bottom-navigation#47]
I would prefer to change the content of the stacklayout instead of using manual routing (this.$navigateTo(page)) way.

I want to achieve similar to when using TabView, however TabView doesn't shrink its TabViewItem when we have more than 3 TabViewItems.

Please help.

**Comment by henrychavez** [comment]
Hi, 

you can try with this plugin [https://github.com/lmiller1990/v-switch-case](https://github.com/lmiller1990/v-switch-case)

or search for conditional rendering for Vue. There are a `v-if`, `v-else` directives but I don't know if can be applied multiple times if not search for conditional rendering for Vue and you can find a solution

In Angular, we have `ngSwitch` so it's easier to do what you want to accomplish.

**Comment by syahnur197** [comment]
hello sir, i tried v-if after posting this issue. it works!! thank you very much

**Comment by henrychavez** [comment]
That's great!

Happy coding 😄
