### ISSUE TITLE
 Error: Could not load view for: nativebottomnavigation

### ISSUE THREAD

**Issue by pistol88** [henrychavez/nativescript-bottom-navigation#49]
Hi there.

I've installed this

```npm i nativescript-bottom-navigation```

And tried to use with the blank Vue application

app.js
```
Vue.registerElement('BottomNavigation', () => require('nativescript-bottom-navigation').BottomNavigation);
Vue.registerElement('BottomNavigationTab', () => require('nativescript-bottom-navigation').BottomNavigationTab);
```

Home.Vue
```
        <GridLayout rows="*, auto">
            <StackLayout row="0">
               <Label text="content"></Label>
            </StackLayout>
            <BottomNavigation activeColor="red"
                              inactiveColor="yellow"
                              backgroundColor="black"
                              keyLineColor="black"

                              row="1">
                <BottomNavigationTab title="First" icon="ic_home" />
                <BottomNavigationTab title="Second" icon="ic_view_list" />
                <BottomNavigationTab title="Third" icon="ic_menu" />
            </BottomNavigation>
        </GridLayout>
```

It causes error at console (use preview at Iphone 7)

```2019-02-01 23:25:47.498 nsplaydev[2716:1033934] Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: Could not load view for: nativebottomnavigation. ReferenceError: Can't find variable: MDCBottomNavigationBarDelegate```

tns version: 5.1.1
npm version: 5.5.1

packages.json

```
    "dependencies": {
        "nativescript-bottom-navigation": "^1.4.4",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-vue": "~2.0.0",
        "tns-core-modules": "~5.1.0"
    },
    "devDependencies": {
        "@babel/core": "~7.1.0",
        "@babel/preset-env": "~7.1.0",
        "babel-loader": "~8.0.0",
        "nativescript-dev-webpack": "~0.19.0",
        "nativescript-vue-template-compiler": "~2.0.0",
        "node-sass": "~4.9.0",
        "vue-loader": "~15.4.0"
    },
```

thank you!

**Comment by henrychavez** [comment]
You need to import de component in your vue file too

**Comment by henrychavez** [comment]
I suggest you to always install a plugin with the command `tns plugin add your-plugin` what you can do is run `tns plugin remove nativescript-bottom-navigation, then added it again using the command above and run the compilation for ios.

If you still have the error just delete your `platform/ios` folder and run the compilation again.
