### ISSUE TITLE
Badge with no value, just as notification indicator

### ISSUE THREAD

**Issue by keerl** [henrychavez/nativescript-bottom-navigation#52]
I am using a badge on the icons, but for my case I don't really want numbers in them. I would simply just want a smaller red dot to indicate a notification. If I set the badgeValue to an empty string, it works great on iOS, but it doesn't show up on Android. If I make the badgeValue a space it appears on both, but they are obnoxiously big. [See pictures.](https://imgur.com/a/Gp6vcc6)

Is it possible to implement this feature on Android?

### Which platform(s) does your issue occur on?
- Android

### Is there any code involved? 
        const tabIndex = 1;
        const badgeValue = ""; 

        if (isIOS) {
            const tab = this._bottomNavigation.ios.items[tabIndex];
            tab.badgeValue = badgeValue;
        } else {
            // Android
            this._bottomNavigation.android.setNotification(badgeValue, tabIndex);
        }

**Comment by henrychavez** [comment]
solved in version 2.0.0, please review the README file
