### ISSUE TITLE
iOS. Events issues after selectTab() function usage

### ISSUE THREAD

**Issue by pichurichko** [henrychavez/nativescript-bottom-navigation#57]
Using **selectTab** function to select second tab leads to event issues when clicking first (default) tab.

Clicking first tab fires **tabReselected** event instead of **tabSelected** event.

Problem found updating app plugin version from **1.3.0** to **1.5.0**.

**Comment by henrychavez** [comment]
Thanks,

I'll review this, can you please tell me if this error occurs is both platforms?

**Comment by pichurichko** [comment]
@henrychavez np, thank you, too.

This problem occurs only on iOS.

**Comment by henrychavez** [comment]
I just release the version 1.5.1 with the fix.

Happy coding!
