### ISSUE TITLE
Tab highlighting always a step behind

### ISSUE THREAD

**Issue by blake78** [henrychavez/nativescript-bottom-navigation#6]
Here's my code for when a tab is selected:

`    onBottomNavigationTabSelected(args: OnTabSelectedEventData): void {
      switch(args.newIndex){
        case 0:
          this.router.navigate(['home/']);
          break;
        case 1:
          this.router.navigate(['search/' + "something"]);
          break;
        case 2:
          this.router.navigate(['user/']);
          break;
      }
    }
`

and my tabs in the xml:
`    <BottomNavigation [tabs]="tabs"
                      activeColor="red"
                      inactiveColor="yellow"
                      backgroundColor="black"
                      (tabSelected)="onBottomNavigationTabSelected($event)"
                      row="1"></BottomNavigation>
`

Yet, when I click the tabs in the navigation, it always takes two "taps" to get it to highlight in red.  Like the highlighting is actually based on the args.oldIndex or something.

Am I implementing the code incorrectly?

thanks,
Blake

**Comment by henrychavez** [comment]
@blake78 is this issue for Android or iOS?

**Comment by henrychavez** [comment]
@blake78 also the implementation it's not the correct the point of use a bottom navigation is to render the content of the page without navigate to another.

If you want please give me an email and I can send you and example using ngSwitch
