### ISSUE TITLE
Load Tabs from promise

### ISSUE THREAD

**Issue by MichaelSmi** [henrychavez/nativescript-bottom-navigation#63]
**Problem:**
I need to load the tabs from local sqlite database so the result is only available in promise.
Is there any way to make the tabs "wait" for the tabs binding variable to be set?

**Which platform(s) does your issue occur on?**
- [x] iOS 12
- [ ] Android

**What type of device?**
- [ ] Emulator
- [x] Device

**Please, provide the following version numbers that your issue occurs with:**

- CLI:
tns --version: 5.4.0

**Is there any code involved?**

I call the following promise function inside the *onload* event:
`itemComponent.setNavigationItems(args, "tabs")`
But when I set the *tabs* data binding object it is "undefined" because the tabs init function will not wait for the promise :(

BTW: The below code is also much better to prevent overwriting other binding data. This could improve your docs!
```
page.bindingContext = Object.assign({
            tabs: [
                new BottomNav.BottomNavigationTab("First", "ic_home"),
                new BottomNav.BottomNavigationTab("Second", "ic_view_list"),
                new BottomNav.BottomNavigationTab("Third", "ic_menu"),
            ]
        },
        page.bindingContext);
´´´

**Comment by henrychavez** [comment]
Hi,
I need a better example of what you are trying to do because the component creates the tabs when you set values to the `tabs` property 

as you can see 

```typescript
[tabsProperty.setNative](value: BottomNavigationTab[]) {
    this.createTabs(value);
}
```
can you show me how you are doing the promise and setting the value for the tabs? because one of the problems can be that you are not using an `observable` for your `bindingContext`

**Comment by henrychavez** [comment]
closed due to inactivity
