### ISSUE TITLE
[FEATURE] Integrate your component into nativescript-material-components

### ISSUE THREAD

**Issue by farfromrefug** [henrychavez/nativescript-bottom-navigation#64]
Hy @henrychavez love your component!
I want to add a bottom navigation to [```nativescript-material-components```](https://github.com/Akylas/nativescript-material-components)
As you might now inside ```nativescript-material-components``` we try to have native components  only based on [material-components-android](https://github.com/material-components/material-components-android) and [material-components-ios](https://github.com/material-components/material-components-ios)
Your implementation for ios is using it but not your android one.

Would be willing to help on migrating your component to ```nativescript-material-components``` and implementing the android based [this](https://github.com/material-components/material-components-android/blob/master/docs/components/BottomNavigationView.md) ?

**Comment by henrychavez** [comment]
Hi @farfromrefug,
Yes, I would like to do that, let me know how you wanna do this.

You can email me if you want: henry19.chavez@gmail.com
