### ISSUE TITLE
App crashes in iOS after updating Nativescript to v6

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [henrychavez/nativescript-bottom-navigation#70]
Hello,

  after updating the NS to v6, I am getting this error
  **undefined is not an object (evaluating 'owner.items.length')**

  it was previously working fine...

  Please help.

**Comment by henrychavez** [comment]
Hello,

are you sure the plugin is causing that error? because that code doesn't exist in the source code

**Comment by TaiTran95** [comment]
I also use this plugin on NS6.0 and it work fine on both Android and iOS.

**Comment by ishaqueahmed-mev** [comment]
Hello,

I don't exactly know, but whenever I redirect to the tabs page, the app crashes. Also after downgrading NS to v5.4.2 it is again working fine.

Thanks.

**Comment by henrychavez** [comment]
The  version `2.0.0` was released with support for NS6 and fix the issues releaded with component name, please review the README file
