### ISSUE TITLE
[BUG] non abstract class BottomNavigationBarBase doesnt implement members

### ISSUE THREAD

**Issue by johnny-stevie** [henrychavez/nativescript-bottom-navigation#71]
**Before start:**
 - Make sure to check the demo app(s) for sample usage
 - Make sure to check the existing issues in this repository 
 - If the demo apps cannot help and there is no issue for your problem, tell us about it

---

**Which platform(s) does your issue occur on?**
-  Android

**What type of device?**
-  Emulator
- [ ] Device

**Please, provide the following version numbers that your issue occurs with:**

- CLI: 6
- Cross-platform modules: 
`"@types/node": "~7.0.5",
    "tns-platform-declarations": "next"`
- Runtime(s):  tns run android and tns build android
- Plugin(s): "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "@types/node": "^12.6.8",
    "cheerio-without-node-native": "^0.20.2",
    "htmlparser2-without-node-native": "^3.9.2",
    "nativescript-advanced-webview": "^3.0.2",
    "nativescript-angular": "~8.0.0",
    "nativescript-bottom-navigation": "^2.0.2",
    "nativescript-linearprogressbar": "^1.0.4",
    "nativescript-local-notifications": "^4.0.1",
    "nativescript-permissions": "^1.3.6",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "tns-core-modules": "^6.0.6",
    "zone.js": "~0.9.1"

**Please, tell us how to recreate the issue in as much detail as possible.**
Describe the steps to reproduce the behavior:
Followed instructions in demo where i tried to change tabs in order to navigate between different pages

**Is there any code involved?**
 `@ViewChild('bottomNavigationBar', { read: ElementRef, static: false })
  private _bottomNavigationBar: ElementRef<BottomNavigationBar>;
  
  onbottomNavigationBarLoaded(): void {
    const bottomNavigationBar = this._bottomNavigationBar.nativeElement;
    bottomNavigationBar.showBadge(1);
    bottomNavigationBar.showBadge(2, 4);
  }

  onBottomNavigationTabSelected(args:TabSelectedEventData):void{
    switch (args.newIndex){
      case 0:
        this.router.navigate(["home"],{
          transition:{
            name:"slideRight",
            duration:100,
            curve:"linear"
          },
          queryParams: {
            searchQuery:this.searchQuery
          }});
        break;
      case 1:
          this.routerExtensions.backToPreviousPage();
          break;
      default:
          break;
    }
  }
  onBottomNavigationTabPressed(args: TabPressedEventData): void {
    switch (args.index){
      case 0:
        this.router.navigate(["home"],{
          transition:{
            name:"slideRight",
            duration:100,
            curve:"linear"
          },
          queryParams: {
            searchQuery:this.searchQuery
          }});
        break;
      case 1:
          this.routerExtensions.backToPreviousPage();
          break;
      default:
          break;
    }
  }
  onBottomNavigationTabReselected(args: TabReselectedEventData): void {
    switch (args.index){
      case 0:
        this.router.navigate(["home"],{
          transition:{
            name:"slideRight",
            duration:100,
            curve:"linear"
          },
          queryParams: {
            searchQuery:this.searchQuery
          }});
        break;
      case 1:
          this.routerExtensions.backToPreviousPage();
          break;
      default:
          break;
    }
  }`

The cause of errors:
`ERROR in node_modules/nativescript-bottom-navigation/index.d.ts(14,22): errorember 'createTabs' from class 'BottomNavigationBarBase'.
node_modules/nativescript-bottom-navigation/index.d.ts(14,22): error TS2515: lectTabNative' from class 'BottomNavigationBarBase'.
node_modules/nativescript-bottom-navigation/index.d.ts(53,22): error TS2515: tNativeIcon' from class 'BottomNavigationTabBase'.`

https://github.com/johnny-stevie/ytDownloader

**Comment by henrychavez** [comment]
Thanks for reporting this issue was a typings error, the fix is in the version 2.0.3 that will be available in a couple of minutes 👍

**Comment by johnny-stevie** [comment]
Hello @henrychavez i updated the plugin and I get two main errors, however they dont stop the app weidly:
1.whenever i go to a page with two bottom tabs
`ERROR TypeError: Cannot read property 'nativeElement' of undefined
JS: ERROR CONTEXT {
JS:   "view": {
JS:     "def": {
JS:       "nodeFlags": 704823297,
JS:       "rootNodeFlags": 704643073,
JS:       "nodeMatchedQueries": 0,
JS:       "flags": 0,
JS:       "nodes": [
JS:         {
JS:           "nodeIndex": 0,
JS:           "parent": null,
JS:           "renderParent": null,
JS:           "bindingIndex": 0,
JS:           "outputIndex": 0,
JS:           "checkIndex": -1,
JS:           "flags": 671088640,
JS:           "childFlags": 0,
JS:           "directChildFlags": 0,
JS:           "childMatchedQueries": 0,
JS:           "ngContentIndex": -1,
JS:           "matchedQueries": {},
JS:           "matchedQueryIds": 0,
JS:           "references": {},
JS:           "childCount": 0,
JS:           "bindings": [],
JS:           "bindingFlags": 0,
JS:           "outputs": [],
JS:           "element": null,
JS:           "provider": null,
JS:           "text": null,
JS:           "query": {
JS:             "id": 1,
JS:             "filterId": 2,
JS:             "bindings": [
JS:               {
JS:                 "propName": "_bottomNavigationBar",
JS:                 "bindingType": 0
JS:               }
JS:             ]
JS:           },...
`
2.whenever I start the app
`ERROR in node_modules/nativescript-bottom-navigation/index.d.ts(21,3): error TS2416: Property 'activeColor' in type 'BottomNavigationBar' is not assignable to the same property in base type 'BottomNavigationBarBase'.
  Type 'string' is not assignable to type 'Color'.
node_modules/nativescript-bottom-navigation/index.d.ts(22,3): error TS2416: Property 'inactiveColor' in type 'BottomNavigationBar' is not assignable to the same property in base type 'BottomNavigationBarBase'.
  Type 'string' is not assignable to type 'Color'.
node_modules/nativescript-bottom-navigation/index.d.ts(23,20): error TS2304: Cannot find name 'Color'.
node_modules/nativescript-bottom-navigation/index.d.ts(46,22): error TS2304: Cannot find name 'EventData'`
I think this is easily fixed because you forgot to import the Color and Event Data libs, but I don't know about the active and inactive Color error. Any advice?
