### ISSUE TITLE
tabs property on iOS doesn't work (angular) [BUG] 

### ISSUE THREAD

**Issue by keerl** [henrychavez/nativescript-bottom-navigation#75]
I have just updated to the newest version and I am having an issue with creating the tabs dynamically with the `tabs` property. The tab bar appears, but the tabs themselves are not there. I can create the same tabs inline in the HTML and that works fine, but not when I set them dynamically.

I attached an example of this problem. It is essentially the demo but I changed the tabs from being created inline to be using the `tabs` property.

[bottom-navigation-ios-bug.zip](https://github.com/henrychavez/nativescript-bottom-navigation/files/3587118/bottom-navigation-ios-bug.zip)

**Comment by henrychavez** [comment]
Hi @keerl,

please make sure to read the README.md file, there you can find the breaking changes in the latest version, also you can check the demo projects.

**Comment by keerl** [comment]
I have read the README and changed everything to the newest specs.

**Comment by keerl** [comment]
Please try running my attached project before dismissing me and see that it doesn't work on iOS but it works fine on Android. It is based off your newest demo-ng code with just a little change on how the tabs are created.

**Comment by henrychavez** [comment]
@keerl you were right, the issue will be fixed in the next release 2.0.5 in a couple of minutes.
